# Generated by Django 4.0b1 on 2021-11-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('classification', models.DecimalField(decimal_places=20, max_digits=30)),
                ('size', models.DecimalField(decimal_places=20, max_digits=30)),
                ('kcal', models.DecimalField(decimal_places=20, max_digits=30)),
                ('moisture', models.DecimalField(decimal_places=20, max_digits=30)),
                ('protein', models.DecimalField(decimal_places=20, max_digits=30)),
                ('fat', models.DecimalField(decimal_places=20, max_digits=30)),
                ('carbohydrate', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Total', models.DecimalField(decimal_places=20, max_digits=30)),
                ('dietary_fiber', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Ca', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Fe', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Mg', models.DecimalField(decimal_places=20, max_digits=30)),
                ('P', models.DecimalField(decimal_places=20, max_digits=30)),
                ('K', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Na', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Zn', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Cu', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Vitamin_D', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Vitamin_K', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Vitamin_B1', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Vitamin_B2', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Vitamin_B12', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Vitamin_C', models.DecimalField(decimal_places=20, max_digits=30)),
                ('total_amino_acids', models.DecimalField(decimal_places=20, max_digits=30)),
                ('essential_amino_acids', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Phenylalanine', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Cholesterol', models.DecimalField(decimal_places=20, max_digits=30)),
                ('total_fatty_acids', models.DecimalField(decimal_places=20, max_digits=30)),
                ('total_essential_fatty_acids', models.DecimalField(decimal_places=20, max_digits=30)),
                ('total_saturated_fatty_acids', models.DecimalField(decimal_places=20, max_digits=30)),
                ('total_polyunsaturated_fatty_acids', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Omega_3_fatty_acids', models.DecimalField(decimal_places=20, max_digits=30)),
                ('trans_fatty_acids', models.DecimalField(decimal_places=20, max_digits=30)),
                ('folate', models.DecimalField(decimal_places=20, max_digits=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
