# Generated by Django 4.0b1 on 2021-11-17 15:19

from django.db import migrations, models
import mypage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mypage.utils.upload_image),
        ),
    ]
