# Generated by Django 4.0rc1 on 2021-12-06 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search', to='users.user'),
        ),
        migrations.AddField(
            model_name='searchimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_image', to='users.user'),
        ),
    ]
